
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: mysql2
  database: bookify_database
  username: root
  password: welcome123
  host: localhost

test:
  adapter: mysql2
  database: bookify_database_test
  username: root
  password: welcome123
  host: localhost

production:
  adapter: mysql2
  database: bookify_database_production
  username: root
  password: welcome123
  host: localhost
